{% set version = "0.61.0" %}

package:
  name: memory_profiler
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/memory_profiler/memory_profiler-{{ version }}.tar.gz
  sha256: 4e5b73d7864a1d1292fb76a03e82a3e78ef934d06828a698d9dada76da2067b0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mprof = mprof:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - psutil

test:
  requires:
    - python {{ python_min }}
  imports:
    - memory_profiler
    - mprof
  commands:
    - mprof list
    - python -m memory_profiler --help

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: A module for monitoring memory usage of a python program
  dev_url: https://github.com/pythonprofilers/memory_profiler

extra:
  recipe-maintainers:
    - jakirkham
    - carlodri
