{% set version = "0.50.0" %}

package:
  name: memory_profiler
  version: {{ version }}

source:
  fn: memory_profiler-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/memory_profiler/memory_profiler-{{ version }}.tar.gz
  sha256: 99bc5be2597af4cd5ed3ec7323961a27b3c5b20d8503aa4e7e3a5321b024e547

build:
  noarch: python
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - psutil

test:
  imports:
    - memory_profiler

  commands:
    - mprof list
    - python -m memory_profiler --help

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: BSD 3-Clause
  license_family: BSD
  # Not yet included. Please see PR for addition.
  #
  # https://github.com/fabianp/memory_profiler/pull/124
  #
  # license_file: COPYING
  summary: A module for monitoring memory usage of a python program

extra:
  recipe-maintainers:
    - jakirkham
